version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: university
      POSTGRES_USER: pupkin
      POSTGRES_PASSWORD: zupkin
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  python-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - ./output:/app/output
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: university
      DB_USER: pupkin
      DB_PASSWORD: zupkin
